### ISSUE TITLE
Hello, I encountered error while dealing AnnotSV with vcf file output from Delly.

### ISSUE THREAD

**Issue by minn333** [mobidic/knotAnnotSV#13]
AnnotSV version: AnnotSV_3.0.9

Command line:
$ANNOTSV/bin/AnnotSV -SVinputFile $files -genomeBuild GRCh37 -outputFile "${files%%.*}"_output_t3.tsv -svtBEDcol 4 >& "${files%%.*}"_out.log

The error.log as below:
 
AnnotSV
130109_AnnotSV_inputSVfile.formatted.sorted.bed -b path to/AnnotSV/Annotations_Human/Genes/GRCh37/genes.RefSeq.sorted.bed -wa -wb > path to/$SampleID_delly_sv_output_t3.tsv.tmp.tmp
Error: Invalid record in file path to/20220505-130109_AnnotSV_inputSVfile.formatted.sorted.bed. Record is
17      -54     1077    BND     $SampleID     BND00215903     A       ]chr14:33953985]A       180     LowQual IMPRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.8.7;END=512;CHR2=chr14;POS2=33953985;PE=3;MAPQ=60;CT=5to3;CIPOS=-565,565;CIEND=-565,565      GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 0/1:-15.2495,0,-249.25:152:PASS:23011:46179:23168:2:44:5:0:0
Exit with error
 
Delly VCF file (extraction error line)
chr17     511 BND00215903    A     ]chr14:33953985]A  180 LowQual        IMPRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.8.7;END=512;CHR2=chr14;POS2=33953985;PE=3;MAPQ=60;CT=5to3;CIPOS=-565,565;CIEND=-565,565        GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV        0/1:-15.2495,0,-249.25:152:PASS:23011:46179:23168:2:44:5:0:0
-------------------------------------------------------------------------------------

attached vcf file as xlsx file for test as below:

[sampleIDforGithub_delly_sv.vcf.xlsx](https://github.com/mobidic/knotAnnotSV/files/8644447/sampleIDforGithub_delly_sv.vcf.xlsx)

**Comment by lgmgeo** [comment]
Hi @minn333,

This is an annotation bug (with [AnnotSV](https://github.com/lgmgeo/AnnotSV/issues)) rather than a visualization bug (with [knotAnnotSV](https://github.com/mobidic/knotAnnotSV/issues)).

Your confidence interval around the start position is `CIPOS=-565,565`.
AnnotSV evaluates this start position as follows: start = 511 - 565 = -54
Of course, this negative coordinate is not possible... and causes the bug.

Please, use AnnotSV with the `-includeCI` option set to "no", this should solve your bug.

I will add a bugfix for that in the future python version.

Best regards,
Véronique

**Comment by minn333** [comment]
Hello @lgmgeo 
         Thanks for your kindly reply and solving my problem, I will try as your suggestion.

**Comment by minn333** [comment]
Dear @lgmgeo 
                  I ran the AnnotSV as your suggestion, the tools didn't go smoothly to the output files. The files I got is listed as below:
$SampleID.SV_RE_intersect.tmp
$SampleID_output.tmp
$SampleID.unannotated.tsv
and log file.

The content of log file as below. Could you kindly tell me what the problem I had met?

Thanks,...
by Duan
               
     ******************************************
        AnnotSV has been run with these arguments:
        ******************************************
        -REreport no
        -SVinputFile $path/$SampleID_delly_sv.vcf
        -SVinputInfo 1
        -SVminSize 50
        -annotationMode both
        -annotationsDir $Path/AnnotSV/AnnotSV_v3.0.9/share/AnnotSV
        -bcftools bcftools
        -bedtools bedtools
        -candidateGenesFiltering no
        -genomeBuild GRCh37
        -includeCI no
        -metrics us
        -minTotalNumber 500
        -organism Human
        -outputDir $Path-to-output directory
        -outputFile $SampleID_delly_sv_output_t3.tsv
        -overlap 100
        -overwrite yes
        -promoterSize 500
        -rankFiltering 1 2 3 4 5 NA
        -reciprocal no
        -samplesidBEDcol -1
        -snvIndelPASS 0
        -svtBEDcol 4
        -tx RefSeq
        ******************************************

max length of a Tcl list (536870909 elements) exceeded
    while executing
"lappend L_allRegulatedGenes {*}[split [lindex $Ls end] ";"]"
    (procedure "regulatoryElementsAnnotation" line 45)
    invoked from within
"regulatoryElementsAnnotation $L_allGenesOverlapped"
    (procedure "genesAnnotation" line 386)
    invoked from within
"genesAnnotation"
    (file "$path/AnnotSV/AnnotSV_v3.0.9/bin/AnnotSV" line 270)

**Comment by lgmgeo** [comment]
I think you are trying to annotate a very large SV input file.

Please refer to this:
https://github.com/lgmgeo/AnnotSV/issues/15#issuecomment-642920870

The future reimplementation in Python should fix this bug.
Sorry for the inconvenience.

**Comment by minn333** [comment]
Dear @lgmgeo 
           Thanks for your kindly reply. I had met another problem while running smaller VCF files. The log file as below: 
the problem of overlap -100?, how can i solve this problem to finish my annotation?

Thanks..

---------------------------------------------------------------------------------------

...checking the annotation data sources

WARNING: No GeneHancer annotations available.
(Please, see in the README file how to add these annotations. Users need to contact the GeneCards team.)


...listing arguments
        ******************************************
        AnnotSV has been run with these arguments:
        ******************************************
        -REreport no
        -SVinputFile /$path/Delly_smallfiles/$sampleID_delly_sv.vcf
        -SVinputInfo 1
        -SVminSize 50
        -annotationMode both
        -annotationsDir /$path/AnnotSV/AnnotSV_v3.0.9/share/AnnotSV
        -bcftools bcftools
        -bedtools bedtools
        -candidateGenesFiltering no
        -genomeBuild GRCh37
        -includeCI no
        -metrics us
        -minTotalNumber 500
        -organism Human
        -outputDir /path/Delly_smallfiles
        -outputFile $sampleID_delly_sv_output_t3.tsv
        -overlap 100
        -overwrite yes
        -promoterSize 500
        -rankFiltering 1 2 3 4 5 NA
        -reciprocal no
        -samplesidBEDcol -1
        -snvIndelPASS 0
        -svtBEDcol 4
        -tx RefSeq
        ******************************************

...searching for SV overlaps with a gene or a regulatory elements
        ...28035 genes overlapped with an SV

**Comment by lgmgeo** [comment]
Hi @minn333,

Can you please post your issue in [AnnotSV](https://github.com/lgmgeo/AnnotSV/issues)?
It is not the rigth place here (you're in the knotAnnotSV github).

Regarding on your description, I can't see any error message. 
Can you give me all the AnnotSV output ? (in a new issue)

Best,
Véronique

**Comment by lgmgeo** [comment]
cf https://github.com/lgmgeo/AnnotSV/issues/125#issue-1233980876

Thomas, can you close this issue?
