### ISSUE TITLE
Sensitive data analysis

### ISSUE THREAD

**Issue by priyambial123** [mobidic/knotAnnotSV#14]
I am working as a postdoc in University of Basel, Switzerland. Due to the data protection rights in Switzerland, the sequence data is protected and not shared with other groups. I am interested to use the Knot AnnotSV web application to visualize the annotated data.  VCF is anonymized.  It is clear that the analyzed data will be deleted after one month. Can you let me know if there is any data protection measures for such sensitive data to analyze in the Knot Annot SV application. 

Thanks

**Comment by lgmgeo** [comment]
Hi @priyambial123,

Like AnnotSV, knotAnnotSV can be run locally. This is the best way to ensure data protection.

Best,

Véronique
