### ISSUE TITLE
failed with exomiser not found

### ISSUE THREAD

**Issue by lmanchon** [mobidic/knotAnnotSV#17]
Parsing config file....
Parsing AnnotSV header in order to get column names ...
Undefined field (typo error in config file or absent in annotation file (ex: exomiser):  Human_pheno_evidence in Exomiser_gene_pheno_score
Undefined field (typo error in config file or absent in annotation file (ex: exomiser):  Mouse_pheno_evidence in Exomiser_gene_pheno_score
Undefined field (typo error in config file or absent in annotation file (ex: exomiser):  Fish_pheno_evidence in Exomiser_gene_pheno_score
Argument "NA" isn't numeric in numeric ge (>=) at ./knotAnnotSV2XL.pl line 976, <VCF> line 3.
Can't call method "add_vba_project" on an undefined value at ./knotAnnotSV2XL.pl line 1079, <VCF> line 2040.

conf file "config_AnnotSV.yaml" was:

##################################
AnnotSV_ID:    #mandatory in first position
    POSITION: 1
    RENAME: "AnnotSV ID"
ACMG_class:  # mandatory
    POSITION: 2
    RENAME: "ACMG class"
    HEADERTIPS: "SV ranking class (from 1 to 5) following the 2020 joint consensus recommendation of ACMG and ClinGen"
    COMMENTLIST:
        - AnnotSV_ranking_score
        - AnnotSV_ranking_criteria
SV_type:
    POSITION: 3
    RENAME: "SV type"
    HEADERTIPS: "Type of the SV (DEL, DUP...)"
    COMMENTLIST:
        - SV_length
        - Gene_count

Annotation_mode: #mandatory
    POSITION: 4
    RENAME: "Annotation mode"
    HEADERTIPS: "Type of annotation lines generated:<br>
- annotation on the SV full length (full)<br>
- annotation on each gene overlapped by the SV (split)"

####################
Gene_name:     # mandatory
    POSITION: 5
    RENAME: "Gene name"
    HEADERTIPS: "Gene symbol"
    COMMENTLIST:
        - LOEUF_bin
        - GnomAD_pLI
        - ExAC_pLI
        - HI
        - TS
        - DDD_HI_percent
        - ACMG
        - ExAC_cnvZ
        - ExAC_delZ
        - ExAC_dupZ
        - ExAC_synZ
        - ExAC_misZ
        - GenCC_disease
        - GenCC_moi
        - GenCC_classification
        - GenCC_pmid
Location:
    POSITION: 6
    RENAME: "Location"
    HEADERTIPS: "Hover your mouse to highlight SV location annotations in the gene"
    COMMENTLIST:
        - CytoBand
        - Location2
        - Tx
        - Tx_start
        - Tx_end
        - Exon_count
        - Overlapped_tx_length
        - Overlapped_CDS_length
        - Overlapped_CDS_percent
        - Frameshift
        - Dist_nearest_SS
        - Nearest_SS_type
        - Intersect_start
        - Intersect_end
OMIM_ID:
    POSITION: 7
    RENAME: "OMIM ID"
    HEADERTIPS: "Hover your mouse to highlight OMIM annotations"
    COMMENTLIST:
        - OMIM_phenotype
        - OMIM_inheritance
        - OMIM_morbid
        - OMIM_morbid_candidate
Exomiser_gene_pheno_score:
    POSITION: 8
    RENAME: "Exomiser score"
    HEADERTIPS: "Show how close each overlapped gene is to the patient phenotype<br>
    Highly specific and consistent phenotype: score > 0.7<br>
    Consistent phenotype: score > 0.5"
    COMMENTLIST:
        - Human_pheno_evidence
        - Mouse_pheno_evidence
        - Fish_pheno_evidence

#############################################
RE_gene:
    POSITION: 9
    RENAME: "Overlapped regulatory elements"
    HEADERTIPS: "Report the name of the genes potentially badly regulated"

#######################################
P_gain_coord:
    POSITION: 10
    RENAME: "Pathogenic SV"
    HEADERTIPS: "Known pathogenic genes or genomic regions (with the same SV type; from ClinVar, ClinGen, dbVar, OMIM) completely overlapped with the SV to annotate"
    COMMENTLIST:
        - P_gain_source
        - P_gain_phen
        - P_gain_hpo
        - P_loss_coord
        - P_loss_source
        - P_loss_phen
        - P_loss_hpo
        - po_P_gain_phen
        - po_P_gain_hpo
        - po_P_gain_source
        - po_P_gain_coord
        - po_P_gain_percent
        - po_P_loss_phen
        - po_P_loss_hpo
        - po_P_loss_source
        - po_P_loss_coord
        - po_P_loss_percent

##############################################
P_snvindel_nb:
    POSITION: 11
    RENAME: "Number of pathogenic SNV/indel overlapped"
    HEADERTIPS: "Pathogenic SNV/indel (from ClinVar) completely overlapped with the SV to annotate"
    COMMENTLIST:
        - P_snvindel_phen

###################################
B_gain_source:
    POSITION: 12
    RENAME: "Benign SV"
    HEADERTIPS: "Benign genomic regions (with the same SV type; from gnomAD, ClinVar, ClinGen, DGV, DDD, 1000g, IMH) completely overlapping the SV to annotate"
    COMMENTLIST:
        - B_gain_coord
        - B_gain_AFmax
        - B_loss_source
        - B_loss_coord
        - B_loss_AFmax
        - po_B_gain_allG_source
        - po_B_gain_allG_coord
        - po_B_gain_someG_source
        - po_B_gain_someG_coord
        - po_B_loss_allG_source
        - po_B_loss_allG_coord
        - po_B_loss_someG_source
        - po_B_loss_someG_coord

##################################
ENCODE_blacklist_characteristics_left:
    POSITION: 13
    RENAME: "Left breakpoint annotations"
    HEADERTIPS: "Hover your mouse to highlight the left SV breakpoint (+/- 100bp) annotations"
    COMMENTLIST:
        - ENCODE_blacklist_left
        - SegDup_left
        - Repeat_coord_left
        - Repeat_type_left
        - Gap_left
        - GC_content_left

ENCODE_blacklist_characteristics_right:
    POSITION: 14
    RENAME: "Right breakpoint annotations"
    HEADERTIPS: "Hover your mouse to highlight the right SV breakpoint (+/- 100bp) annotations"
    COMMENTLIST:
        - ENCODE_blacklist_right
        - SegDup_right
        - Repeat_coord_right
        - Repeat_type_right
        - Gap_right
        - GC_content_right

TAD_coordinate:
    POSITION: 0
ENCODE_experiment:
    POSITION: 0
Cosmic_ID:
    POSITION: 0
Cosmic_mut_typ:
    POSITION: 0
compound-htz(sample):
    POSITION: 0
Count_hom(sample):
    POSITION: 0
Count_htz(sample):
    POSITION: 0
Count_htz/allHom(sample):
    POSITION: 0
Count_htz/total(cohort):
    POSITION: 0
Count_total(cohort):
    POSITION: 0

**Comment by lgmgeo** [comment]
Can you advise the version of knotAnnotSV used?
And can you give your command line?

**Comment by thomasguignard** [comment]
The file vbaProject.bin should be in the same directory as the perl script, that may explain this: 
_Can't call method "add_vba_project" on an undefined value at ./knotAnnotSV2XL.pl line 1079, line 2040._

For the undefined fields, be sure that your annotation file (tsv) contains exomiser annotation (check the tsv header).

**Comment by lmanchon** [comment]
AnnotSV 3.2.1
knotAnnotSV 1.1

bin/AnnotSV -SVinputFile IC_1000_CNV.bed -snvIndelFiles IC_1000.vcf -outputDir IC_1000_annotSV -outputFile IC_1000_annotSV.tsv -svtBEDcol 4 -SVinputInfo 1 -genomeBuild GRCh38

with IC_1000_CNV.bed:

chr1    56376   6197756 DEL/1
chr10   87933012        133545219       DEL/1
chr11   48891147        50831233        DUP/3
chr12   112450317       133243513       DEL/1
chr13   28308842        28311732        DEL/0
chr16   18859021        18900000        DEL/0
chr16   18901712        38307853        DUP/3
chr17   31223443        31265339        DEL/0
chr17   42218722        42219842        DEL/0
chr19   110955  4117629 DEL/0
chr21   4889470 8162792 DUP/3
chr21   8162792 14072812        DUP/6
chr21   14073312        46674950        DEL/1
chr5    171387948       171410565       DEL/0
chr7    5973398 6402446 DEL/0
chr7    151467118       159219784       DEL/0
chr8    73941555        73959768        DEL/0
chr9    60396086        77720822        DUP/3
chr9    77721322        77922345        DEL/0
chrY    150500  56869545        DEL/0

then:

./knotAnnotSV2XL.pl --annotSVfile IC_1000_annotSV.tsv --outDir IC_1000_knotAnnotSV --configFile ./config_AnnotSV.yaml --outPrefix IC_1000 -genomeBuild GRCh38

and vbaProject.bin is in the same directory as knotAnnotSV2XL.pl:

@icare ~ knotAnnotSV] ls -l
-rw-rw-r--  1 laurent laurent    7900 déc.  20 10:16 config_AnnotSV.yaml
drwxrwxr-x  5 laurent laurent    4096 déc.  20 10:16 DataTables/
drwxrwxr-x  2 laurent laurent    4096 déc.  20 10:24 example/
-rw-rw-r--  1 laurent laurent  172156 mars  23 09:18 example.annotated.tsv
drwxrwxr-x  8 laurent laurent    4096 déc.  20 10:16 .git/
-rw-rw-r--  1 laurent laurent 1615912 mars  23 11:47 IC_1000_annotSV.tsv
drwxrwxr-x  2 laurent laurent    4096 déc.  20 10:16 images/
-rwxr-xr-x  1 laurent laurent   49406 déc.  20 10:16 knotAnnotSV2XL.pl*
-rwxr-xr-x  1 laurent laurent   62302 déc.  20 10:16 knotAnnotSV.pl*
-rw-rw-r--  1 laurent laurent   33093 déc.  20 10:16 License.txt
-rw-rw-r--  1 laurent laurent  981279 déc.  20 10:16 README.knotAnnotSV_latest.pdf
-rw-rw-r--  1 laurent laurent    9362 déc.  20 10:16 README.md
-rw-rw-r--  1 laurent laurent   14848 déc.  20 10:16 vbaProject.bin

with config_AnnotSV.yaml:


AnnotSV_ID:    #mandatory in first position
    POSITION: 1
    RENAME: "AnnotSV ID"
ACMG_class:  # mandatory
    POSITION: 2
    RENAME: "ACMG class"
    HEADERTIPS: "SV ranking class (from 1 to 5) following the 2020 joint consensus recommendation of ACMG and ClinGen"
    COMMENTLIST:
        - AnnotSV_ranking_score
        - AnnotSV_ranking_criteria
SV_type:
    POSITION: 3
    RENAME: "SV type"
    HEADERTIPS: "Type of the SV (DEL, DUP...)"
    COMMENTLIST:
        - SV_length
        - Gene_count

Annotation_mode: #mandatory
    POSITION: 4
    RENAME: "Annotation mode"
    HEADERTIPS: "Type of annotation lines generated:<br>
- annotation on the SV full length (full)<br>
- annotation on each gene overlapped by the SV (split)"

 Gene annotations

Gene_name:     # mandatory
    POSITION: 5
    RENAME: "Gene name"
    HEADERTIPS: "Gene symbol"
    COMMENTLIST:
        - LOEUF_bin
        - GnomAD_pLI
        - ExAC_pLI
        - HI
        - TS
        - DDD_HI_percent
        - ACMG
        - ExAC_cnvZ
        - ExAC_delZ
        - ExAC_dupZ
        - ExAC_synZ
        - ExAC_misZ
        - GenCC_disease
        - GenCC_moi
        - GenCC_classification
        - GenCC_pmid
Location:
    POSITION: 6
    RENAME: "Location"
    HEADERTIPS: "Hover your mouse to highlight SV location annotations in the gene"
    COMMENTLIST:
        - CytoBand
        - Location2
        - Tx
        - Tx_start
        - Tx_end
        - Exon_count
        - Overlapped_tx_length
        - Overlapped_CDS_length
        - Overlapped_CDS_percent
        - Frameshift
        - Dist_nearest_SS
        - Nearest_SS_type
        - Intersect_start
        - Intersect_end
OMIM_ID:
    POSITION: 7
    RENAME: "OMIM ID"
    HEADERTIPS: "Hover your mouse to highlight OMIM annotations"
    COMMENTLIST:
        - OMIM_phenotype
        - OMIM_inheritance
        - OMIM_morbid
        - OMIM_morbid_candidate
Exomiser_gene_pheno_score:
    POSITION: 8
    RENAME: "Exomiser score"
    HEADERTIPS: "Show how close each overlapped gene is to the patient phenotype<br>
    Highly specific and consistent phenotype: score > 0.7<br>
    Consistent phenotype: score > 0.5"
    COMMENTLIST:
        - Human_pheno_evidence
        - Mouse_pheno_evidence
        - Fish_pheno_evidence

Annotations done with regulatory elements

RE_gene:
    POSITION: 9
    RENAME: "Overlapped regulatory elements"
    HEADERTIPS: "Report the name of the genes potentially badly regulated"

Annotations done with pathogenic SV

P_gain_coord:
    POSITION: 10
    RENAME: "Pathogenic SV"
    HEADERTIPS: "Known pathogenic genes or genomic regions (with the same SV type; from ClinVar, ClinGen, dbVar, OMIM) completely overlapped with the SV to annotate"
    COMMENTLIST:
        - P_gain_source
        - P_gain_phen
        - P_gain_hpo
        - P_loss_coord
        - P_loss_source
        - P_loss_phen
        - P_loss_hpo
        - po_P_gain_phen
        - po_P_gain_hpo
        - po_P_gain_source
        - po_P_gain_coord
        - po_P_gain_percent
        - po_P_loss_phen
        - po_P_loss_hpo
        - po_P_loss_source
        - po_P_loss_coord
        - po_P_loss_percent

Annotations done with pathogenic snv/indel

P_snvindel_nb:
    POSITION: 11
    RENAME: "Number of pathogenic SNV/indel overlapped"
    HEADERTIPS: "Pathogenic SNV/indel (from ClinVar) completely overlapped with the SV to annotate"
    COMMENTLIST:
        - P_snvindel_phen

Annotations done with benign SV

B_gain_source:
    POSITION: 12
    RENAME: "Benign SV"
    HEADERTIPS: "Benign genomic regions (with the same SV type; from gnomAD, ClinVar, ClinGen, DGV, DDD, 1000g, IMH) completely overlapping the SV to annotate"
    COMMENTLIST:
        - B_gain_coord
        - B_gain_AFmax
        - B_loss_source
        - B_loss_coord
        - B_loss_AFmax
        - po_B_gain_allG_source
        - po_B_gain_allG_coord
        - po_B_gain_someG_source
        - po_B_gain_someG_coord
        - po_B_loss_allG_source
        - po_B_loss_allG_coord
        - po_B_loss_someG_source
        - po_B_loss_someG_coord

 Annotations of the breakpoints

ENCODE_blacklist_characteristics_left:
    POSITION: 13
    RENAME: "Left breakpoint annotations"
    HEADERTIPS: "Hover your mouse to highlight the left SV breakpoint (+/- 100bp) annotations"
    COMMENTLIST:
        - ENCODE_blacklist_left
        - SegDup_left
        - Repeat_coord_left
        - Repeat_type_left
        - Gap_left
        - GC_content_left

ENCODE_blacklist_characteristics_right:
    POSITION: 14
    RENAME: "Right breakpoint annotations"
    HEADERTIPS: "Hover your mouse to highlight the right SV breakpoint (+/- 100bp) annotations"
    COMMENTLIST:
        - ENCODE_blacklist_right
        - SegDup_right
        - Repeat_coord_right
        - Repeat_type_right
        - Gap_right
        - GC_content_right

TAD_coordinate:
    POSITION: 0
ENCODE_experiment:
    POSITION: 0
Cosmic_ID:
    POSITION: 0
Cosmic_mut_typ:
    POSITION: 0
compound-htz(sample):
    POSITION: 0
Count_hom(sample):
    POSITION: 0
Count_htz(sample):
    POSITION: 0
Count_htz/allHom(sample):
    POSITION: 0
Count_htz/total(cohort):
    POSITION: 0
Count_total(cohort):
    POSITION: 0

**Comment by lgmgeo** [comment]
Hi @lmanchon ,

Have you solved your exomiser issue? If so, tell us how you did.

Else, concerning the AnnotSV command, you use `-svtBEDcol 4` with this sort of line:
```
chr1 56376 6197756 DEL/1
```
It should be best to only have "DEL" in place of "DEL/1"

Best,
Véronique

**Comment by lmanchon** [comment]
yes, absolutly
i've created another column to summarise the CNV count
you can close this issue

**Comment by lgmgeo** [comment]
Thank you for your feed back
