### ISSUE TITLE
Add new columns to html

### ISSUE THREAD

**Issue by ashamehta** [mobidic/knotAnnotSV#9]
Hi,

Is there a way to add columns that I've appended to my AnnotSV output file to the knotAnnotSV html file? I've tried to do this by adding the new column to my config file:
`test_column:
    POSITION: 16`
and to the knotAnnotSV.pl file:
`"test_column"=>"fullsplit",`
in `my %colNameMode`.  

The script does recognize that `test_column` is in my AnnotSV output file but then I get tons of errors like these: 
Use of uninitialized value $1 in hash element at /oak/stanford/groups/euan/tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 768, <VCF> line 2.
Use of uninitialized value $1 in hash element at /oak/stanford/groups/euan/tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 762, <VCF> line 4.
Use of uninitialized value $1 in hash element at /oak/stanford/groups/euan/tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 762, <VCF> line 13.
Use of uninitialized value $1 in hash element at /oak/stanford/groups/euan/tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 762, <VCF> line 15.

The script does finish successfully with a test_column header, but the values in the column are listed as N/A.
Is there another place in knotAnnotSV.pl that I need to update to make this change?

Thanks in advance for your help!

**Comment by thomasguignard** [comment]
Hi, 

you don't need to modify knotAnnotSV.pl, it can already recognize and display new columns if there are correctly written in the config yaml file, as you seemly did. 
And it's also true, if you want to put your custom column as a comment for another column, it will be displayed in full and split mode by default. 
But you can specify it as you did, by adding it  in my %colNameMode.

If you have appended your own columns  to your AnnotSV output file (I guess in a text editor after a annotSV run),  please check first that your 'test_column" values are tab separated (not space separated), and then that the position is the same as the config file says. 
Surprisingly, the errors lines (line 762 an 768) you get has nothing to do with extra columns, but with annotSV ranking criteria. So it sounds like a format problem in your input file. 

An other way to add custom columns is to add them before annotSV run, as additional columns in an input BED file .  

I may further help you if you send me your config file and the 2-3 first lines of your annotSV tsv output file as example.

**Comment by ashamehta** [comment]
Hi,

Thanks for your response.
- I have verified that the test_column values are tab separated in TextEdit.
- My understanding is that POSITION in the config file should correspond to the desired position in the html file, not the existing position in the AnnotSV tsv file. Is that correct?

I have attached an example input file (originally tsv) and config file (originally yaml) below. When I don't modify knotAnnotSV.pl and use these files, I run into the following error: 
```
Parsing config file....
Parsing AnnotSV header in order to get column names ... 
Use of uninitialized value $1 in hash element at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 762, <VCF> line 2.
Use of uninitialized value $1 in hash element at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 756, <VCF> line 4.
...
```
Unfortunately, I will need to be able to add columns to the AnnotSV output tsv, rather than the input BED file. 

Thanks,
Asha
[test_column.annotated.txt](https://github.com/mobidic/knotAnnotSV/files/7122860/test_column.annotated.txt)

[config_AnnotSV.txt](https://github.com/mobidic/knotAnnotSV/files/7122879/config_AnnotSV.txt)

**Comment by ashamehta** [comment]
To clarify my use case, my AnnotSV outputs are too large to create usable html files (they never load in the browser). Therefore, I'd like to pre-filter and sort the AnnotSV output tsv to create an abbreviated html file. 

It seems that any edit I make to the AnnotSV output file produces an error when used as input in knotAnnotSV. For example, I filtered the AnnotSV output tsv for ACMG_class="full=5" and FILTER="PASS", then sorted the data based on decreasing Exomiser_gene_pheno_score to produce the attached filtered file. It appears to have identical formatting as the attached unfiltered file (that successfully produces a knotAnnotSV html), yet is producing this error:
```
Parsing config file....
Parsing AnnotSV header in order to get column names ... 
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 940, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 945, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 948, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 953, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 954, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 966, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 971, <VCF> line 2.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 940, <VCF> line 3.
Use of uninitialized value in concatenation (.) or string at /tool/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 945, <VCF> line 3.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 948, <VCF> line 3.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 953, <VCF> line 3.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 954, <VCF> line 3.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 3.
Use of uninitialized value in concatenation (.) or string at /tools/knotAnnotSV/knotAnnotSV_1.0/knotAnnotSV.pl line 959, <VCF> line 3.
...
```

[unfiltered_annotsv_output_working.txt](https://github.com/mobidic/knotAnnotSV/files/7124331/unfiltered_annotsv_output_working.txt)
[filtered_not_working.annotated.txt](https://github.com/mobidic/knotAnnotSV/files/7124326/filtered_not_working.annotated.txt)
***Note that I've converted these files to txt to upload to Github but are being used as tsv file in AnnotSV/knotAnnotSV

**Comment by thomasguignard** [comment]
First, absolutely correct: POSITION in the config file should correspond to the desired position in the html file, not the existing position in the AnnotSV tsv file.

It seems that the errors come from your test_column.annotated.txt:
- in which your column is written  "test_col" whereas it's written "test_column" in the config file. The column name must be the same.
- When I open your test_column.annotated.txt in my text editor (Vim) there are some unexpected quotation marks surrounding some fields. When I delete them ( in a terminal for example: `sed 's/\"//g' test_column.annotated.txt > test_column.annotated_clean.txt`), it solves the output problem (html is correct and no error lines)

**Comment by ashamehta** [comment]
1. Whoops, I uploaded the wrong config here. I had updated "test_col" to "test_column" but uploaded the wrong one here. 
2. Oh that's sneaky - I don't see those when using nano. I'll try deleting them and running it again.

**Comment by thomasguignard** [comment]
Regarding your filtering problem, I can already say that when you are filtering on ACMG_class="full=5", you keep only "split "lines and loose "full" lines that helps with ranking. You should try to include as well the "full" lines with ACMG_class="5".
But if you want to avoid "full" lines, I must think over it a bit more.

**Comment by thomasguignard** [comment]
Sorry, quotation deletion doesn't bring back test_column values, it's still "NA", I'm looking fro the reason.

**Comment by thomasguignard** [comment]
Ok, I get it.
I don't know the process of the tsv file you are doing but it adds a Windows carriage return character, written ^M in vim, at the end of the line, that's why knotAnnotSV.pl doesn't recognize the column name and puts "NA".
https://stackoverflow.com/questions/5843495/what-does-m-character-mean-in-vim
You should avoid working with windows editor, or remove these characters "^M".

**Comment by ashamehta** [comment]
Thanks for looking into this. That's strange, I don't see ^M (typed as Ctrl+V+M) in either the abbreviated files I added here, nor in the other files that aren't working for me when I search using vim. I did:
```
:set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
:set list
```
and there's no sign of "^M":
<img width="1437" alt="Screen Shot 2021-09-07 at 10 49 56 PM" src="https://user-images.githubusercontent.com/76132194/132453640-51c55249-e21d-47fe-85f5-2b199d48f153.png">

Additionally, when I try the command given in the attached article (`:%s/^M//g`), it says `E486: Pattern not found: ^M`. 

It's also strange, because I'm not working with any Windows editors. How were you able to find the "^M"?

**Comment by thomasguignard** [comment]
That's very sneaky.
How I found that:
If all of your endlines are in windows style, vim will adapt the display, and won't make ^M appear.
If you add new line with non-windows style endline, vim will show you the discordant endline. 
In a terminal, try do this: 
```
cat test_column.annotated.tsv > test_column.annotated.2.tsv
cat >> test_column.annotated.2.tsv
tut
tutu
Ctrl C
```
![image](https://user-images.githubusercontent.com/5467968/132473349-b292752a-fede-46b0-9e93-61b522a134b3.png)

That's just to show you the ^M.
 Here are some tips for your pipeline to remove these ^M.
https://its.ucsc.edu/unix-timeshare/tutorials/clean-ctrl-m.html

I have no idea why you get these ^M. Maybe your editor configuration, or your  file comes from MS-DOS.

**Comment by ashamehta** [comment]
Sorry for my delayed reply. It turns out the ^M was appearing when converting the tsv to and from a pandas dataframe and I was able to get rid of it by specifying lineterminator="\n" in `pd.read_csv` and `pd.to_csv`. That solved the issue and my appended columns are now appearing in the html output.

Thank you for your diligent help!
